### PR TITLE
Master: Fix tests on Windows, add Ruby 3.3, and cleanup CI

### PR DESCRIPTION
**Pull request by johnnyshields**
On Windows, the DateTime class struggles with Float values for certain methods like `#next_year` some reason.

### CODE REVIEW

**Comment by johnnyshields** [comment]
@pitbulk this is ready to be merged.

**Comment by johnnyshields** [comment]
@pitbulk this can be merged independently of the other PRs.

**Comment by pitbulk** [comment]
This PR has a mix of the code to be sent to V2 and the one to master branch

See https://github.com/SAML-Toolkits/ruby-saml/pull/687/files#diff-d57c932f52c1cf52ca2f9028672cc7d038bf9c8200484ddc80e63a212a68e6b3

**Comment by johnnyshields** [comment]
@pitbulk oops! Sorry about that, its now fixed and ready to merge.

**Comment by pitbulk** [comment]
@johnnyshields,  We should also apply this on V2

**Pull request merged**
