### PR TITLE
Make the gem compatible with `--enable-frozen-string-literal`

### PR DESCRIPTION
**Pull request by casperisfine**
This option has been available for a very long time in Ruby, and will probably become the default in the semi-near future.

Ref: https://bugs.ruby-lang.org/issues/20205

### CODE REVIEW

**Comment by johnnyshields** [comment]
@casperisfine it's better to just add the magic comment to the top of every file. I think Rubocop autocorrect can do it.

**Comment by casperisfine** [comment]
@johnnyshields I can do that if you prefer, that's no problem.

**Comment by johnnyshields** [comment]
@pitbulk are you ok with it?

**Comment by casperisfine** [comment]
73b6683c2a202331e74b9890a42d7809a8f7b40a

**Comment by casperisfine** [comment]
Hum, looks like `String#+@` was only added in `2.3`:

```
undefined method `+@' for "_":String (NoMethodError)
```

So I may need to use `String#dup` to preserve compatibility.

**Comment by casperisfine** [comment]
> Also should be a single blank line after the magic comment.

Done.

**Comment by johnnyshields** [comment]
This is already fixed in v2.x branch, so this PR can be closed. @pitbulk

**Pull request closed without merging**
